name: Sync Issues to GitHub Project

on:
  issues:
    types: [opened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add issue to GitHub Project
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: "https://github.com/users/AnthonyShenoud/projects/2"  # Correct format
          github-token: ${{ secrets.GITHUB_TOKEN }}
